// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDp1DEFSlnA0xiy9oiCRPf8ZlslCSFH6nU',
    appId: '1:173072849056:web:fe802870112e500d3c51c5',
    messagingSenderId: '173072849056',
    projectId: 'umpaumpa-pampam57',
    authDomain: 'umpaumpa-pampam57.firebaseapp.com',
    databaseURL: 'https://umpaumpa-pampam57-default-rtdb.firebaseio.com',
    storageBucket: 'umpaumpa-pampam57.appspot.com',
    measurementId: 'G-1T9VR0MSF9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3YMbUB61U7aJZ6jwZ2VFuGlz6E5waWuw',
    appId: '1:173072849056:android:f64778e9a71fe3383c51c5',
    messagingSenderId: '173072849056',
    projectId: 'umpaumpa-pampam57',
    databaseURL: 'https://umpaumpa-pampam57-default-rtdb.firebaseio.com',
    storageBucket: 'umpaumpa-pampam57.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdB6HvrdLbaKaaIa4TkjHhS5Ya8yxrCZs',
    appId: '1:173072849056:ios:13af3691b78773a93c51c5',
    messagingSenderId: '173072849056',
    projectId: 'umpaumpa-pampam57',
    databaseURL: 'https://umpaumpa-pampam57-default-rtdb.firebaseio.com',
    storageBucket: 'umpaumpa-pampam57.appspot.com',
    iosBundleId: 'com.example.makerthon1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdB6HvrdLbaKaaIa4TkjHhS5Ya8yxrCZs',
    appId: '1:173072849056:ios:e24485df33d646803c51c5',
    messagingSenderId: '173072849056',
    projectId: 'umpaumpa-pampam57',
    databaseURL: 'https://umpaumpa-pampam57-default-rtdb.firebaseio.com',
    storageBucket: 'umpaumpa-pampam57.appspot.com',
    iosBundleId: 'com.example.makerthon1.RunnerTests',
  );
}
